config/routes.rb
Stack::Application.routes.draw do

# urls for active admin ( it put itself in )
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
		#Routes files matches the URLS up with our controller

		# I want to add in all the REST urls for 
		#the stories
		# e.g. index, show, new, create
		# edit, update , destory
		resources :stories do

		# this is called a nested resource
		# meaning the urls for commments are on the urls for stories

		resources :comments 

		# becuase votes are related to stories, jus like comments

		resources :votes

	end 

#lets add in a homepage

	root  "stories#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
require 'obscenity/active_model'


class Comment < ActiveRecord::Base


	# a comment belongs to a story
	
	# this is our opposite assiocation

	belongs_to :story


	# validations

	validates :body, length: {minimum: 20}, obscenity: {sanitize: true, replacement: :vowels}



end

app/models/story.rb
class Story < ActiveRecord::Base

# this is a connection in rails
# our stroy has manuy comments

has_many :comments 
has_many :votes

# setup as acts as taggable
acts_as_taggable


# validation rules.....
validates :title, length:{ minimum: 5 }
validates :description, presence: true
validates :url, presence: true, uniqueness: {message: "Has already been added"}


# I want to overwrite the url stucture in activerecord
# activerecord is the rails way to manage models
# to_params is the method we want to overwrite
# I want my title to be something like 7-designer-new
# this is my ID then my title as a url


	def to_param


		 "#{id}-#{title.parameterize}"


	end

	# this is my shortcut to make nice clean urls for our users

	def nice_url

		# i want to take url
		# and i want to remove http://
		# and i want to remove www.
		# gsub is a global substitution  
		url.gsub("http://","").gsub("www.","")
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base


	#  counter_cache keeps how many votes there are in story.rb
	
	#  uses votes_count by default

	belongs_to :story, counter_cache: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	# add a comment to a story

	def new
		# so not param[id] as this would refer to a comment

		# we need to find the story by the story_id

		@story  = Story.find(params[:story_id])


		# find the story and make a new comment on that story

		@comment = @story.comments.new


	end


	# actually add the form data and create a comment
	def create

		@story = Story.find(params[:story_id])

		@comment = @story.comments.new(comment_params)


		if @comment.save

			flash[:success] = "You've added your comment"

			redirect_to story_path(@story)
		
		else

			render "new"
		
		end

	end 


	# lets make a shortcut for grabbing the form data
	# out whitelist for form data

	def comment_params

		params.require(:comment).permit(:body)


	end


end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	#  before we run the show , edit , update and destroy
	# lets find the story we're talkling about 

	before_action :find_story, only:[:show,:edit,:update,:destroy]




	#controllers manage the urls,
	#the data from the models, and our html views

	def index
		@username = "Timothy"
		@now = Time.now

		#@stories = ["google","facebook", "twitter", "linkedin" , "Andy"]


		#set the variable stories
		#to all the records in our story database table

		# @stories = Story.order("created_at desc")

		# @stories = Story.order("votes_count desc, title asc")

		#  if it has ?sort=recent in the url
		# sort by created at
		# if it has nothing, then do the popular ones

		if params[:sort] == "recent"	
			# sort by created at, 


			@stories = Story.order("created_at desc")

		elsif params[:sort]=="featured"

			# sort by featured

			@stories = Story.where(is_featured: true)
							.order("is_featured desc, title asc")
				

		else

			@stories = Story.order("votes_count desc, title asc")
			# sort by popular
		end

		# add in my pagination

		# overwrite the @stories variable with a paginated version

		@stories = @stories.page(params[:page]).per(3)

	end


		# this is the individual story page
	# parms id is the number in the url
	def show
		# @story = Story.find( params[:id] )

	end

	# form for new story

	def new 

	#variables @story goes to the view
	#story.new comes from the model
	 @story = Story.new


	end
	#this is where the form data from new.html.erb view goes

	def create 
		@story = Story.new(story_params)

			# conditional ... if 
			if @story.save

					# lets add a flash of connet to the tell the user we've added this
					flash[:success] = "you've added a link booyaa"




					# go back to the home page 
					redirect_to root_path

			else 

					render "new"

			end

	end

# show the edit form

def edit 

	# @story = Story.find(params[:id])


end

# actually update the database

def update

	# @story = Story.find(params[:id])

	if @story.update(story_params)

		flash[:success] = "All good , all updated"

		redirect_to story_path(@story)
		
		else

			render "edit"

	end

end

# actually destroy the record in the database

def destroy
	@story = Story.find(params[:id])


	@story.destroy

	flash[:success] = "Deleted "

	redirect_to root_path


end



	# shortcut for getting form data
	def story_params

		params.require( :story).permit(:title, :description, :url, :tag_list) 

	end 

	# Shortcut for finding the story from the url

	def find_story

		@story = Story.find(params[:id])




	end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


# just create a vote

# no neeed for a new.html.erb because it doesnt make much sense

	def create


		# again, because we're in the votes controller
		# the story id is found by params[:story_id]

		@story = Story.find(params[:story_id])



		# create instead of new beauce we dont need to worry about validations

		@vote = @story.votes.create

		flash[:success] = "you've voted"


		# redirect_to story_path(@story)


		if params[:back_to] == "home"
			# go to the homepage

			redirect_to root_path

		else

			redirect_to story_path(@story)
		end



	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<h2> Add a comment </h2>

<%= simple_form_for [@story,@comment] do |form| %>

<%= form.input :body, label: "Comment" %>
<%= form.button :submit, "Post comment" %>



<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">

    <!-- tab title .... -->
		<title> <%= content_for :page_title %> - Stack</title> 

		


    <%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
      <h1>
        <%= link_to image_tag("/assets/stack-logo.png"), root_path %>
      </h1>

      <nav>
        <%= link_to "Top", root_path %>
        <%= link_to "Recent", root_path(sort: "recent") %>

        <%= link_to "featured", root_path(sort: "featured") %>

        <%= link_to "Submit", new_story_path %>
      </nav>

    </header>

      
    <article>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </article>

	</body>
</html>

app/views/stories/_form.html.erb
<%= simple_form_for @story  do  |form| %>

<%= form.input :title %>
<%= form.input :description %>
<%= form.input :url, label: "Link" %>
<%= form.input :tag_list, label: "Tags" %>

<%= form.button :submit, "Save Story" %>




<% end %>

app/views/stories/edit.html.erb
<%= content_for :page_title, "edit this story" %>


<h2>Edit this story </h2>


<%= render "form" %>

app/views/stories/index.html.erb
<%= content_for :page_title, "Recent stories" %>

<section class = 'stories'>

	<% @stories.each do |story| %>

		<div class="story">



	<h2> <%= link_to story.title, story.url %> </h2>
	<P> <%= story.description %></P>

	<ul>
		<li> <%= link_to "Upvote", story_votes_path(story, back_to: "home"),  method: :post%></li>
		<li> 

	 <!-- need to check the line aboce 	 -->

		<%= link_to pluralize(story.comments.count, "comment"), story_path(story) %>

		</li>
		
		<li><%=pluralize story.votes.count, "votes"%></li>
		
		<li><%= story.nice_url %></li>

		<li> <%= time_ago_in_words story.created_at %> ago</li>


	</ul>

</div>




<% end %>

</section>


<%= paginate @stories %>

<%= link_to "submit a link", new_story_path %>

app/views/stories/new.html.erb
<%= content_for :page_title, " Add new story"%>


<h2>Add new story</h2>

<%= render "form" %>

app/views/stories/show.html.erb
<%= content_for :page_title, @story.title %>


<!-- individual page -->

<div class ="single_story story">

<h2> 

<%= link_to @story.title,@story.url%>

</h2>

<p>
	
<%= @story.description %>

</p>


<ul> 

	<li>

		<%= link_to "upvote", story_votes_path(@story), 
		method: :post %>

	</li>

	<li><%=pluralize @story.votes.count, "vote"%></li>

	<li><%= @story.nice_url%></li>

	<li><%= time_ago_in_words @story.created_at %> ago </li>

</ul>

<div class= "actions">

	<%= link_to "Edit", edit_story_path(@story), class: "edit"%>

	<%= link_to "Delete", story_path(@story), method: :delete, class: "delete", confirm: "are you sure ?" %>	


</div>

<!--  tags...... -->

<h3><%= pluralize @story.tags.count, "tag" %></h3>

<ul> 

<% @story.tags.each do |tag| %>

<li> <%= tag%> </li>


<% end %>

</ul>




<h3> <%= pluralize @story.comments.count, "comment" %></h3>


<% @story.comments.each do |comment| %>

<div class="comment">
	<%= simple_format comment.body %>



	<p><%=time_ago_in_words comment.created_at%> ago </p>


</div>

<% end %>

	<p> 

		<%= link_to "Add a comment", new_story_comment_path(@story) %>

	</p>

</div>